#import "@local/notes:0.1.0"
#import "@local/common:0.1.0": *

#show: notes.show-crossrefs

#set list(marker: move(dy: 0.4em, circle(fill: luma(30%), radius: 1.5pt)))

#set text(font: "CMU Bright")
#show math.equation: set text(font: "New Computer Modern Math")
#set page(width: 15cm, height: auto, margin: 5mm)
#show heading: it => pad(y: 0.1em, it)

#let Cl = math.italic[Cl]
#let tensor = sym.times.circle
#let ee = $bold(e)$
#let span = $op("span")$

#let recall = env.with(accent: teal.saturate(-20%))[Recall]
#let define = env.with(accent: green.saturate(-50%))[Define]
#let result = env.with(accent: yellow.saturate(-30%))[Result]
#let comment = env.with(accent: purple.saturate(-80%))[Comment]
#let theorem = env.with(accent: red.saturate(-50%))[Theorem]
#let example = env.with(accent: purple.lighten(70%))[Example]

#align(center, text(25pt, weight: "bold")[
	Geometic algebra for #emoji.cupcake & #emoji.coffee
])

These notes supplement an introductory talk on geometric algebra.

= Introduction

Linear algebra is suited to describing _linear_ transformations. Geometric algebra is suited to describing _orthogonal_ transformations --- rotations, reflections, rigid transformations, and so on.

The usual study of othogonal maps from linear algebra is framed in terms of matrices.
Because matrices are so general, using them to describe this subclass of linear maps implies a certain redundancy.
Geometric algebra, on the other hand, is suited only to this subclass, and as a result offers a language for rigid geometry that is often very beautful.

= Definitions

#comment[
	Informally, geometric algebra is what you get when you define multiplication of orthonormal basis vectors $RR^n = op("span"){ee_1, ..., ee_n}$ by the rule
	$
		ee_i ee_j = -ee_j ee_i
	$
	whenever $i != j$ and $ee_i^2 = plus.minus 1$, depending on the _signature_ of the space.
]

#example[
	The geometric algebra of 3D Euclidean space is
	$
		Cl(3) = "span"{1, space ee_1, ee_2, ee_3, space ee_2 ee_3, ee_3 ee_1, ee_1 ee_2, space ee_1 ee_2 ee_3 }
	$
	with $e_i^2 = 1$ and therefore $(e_i e_j)^2 = -1$ and $II^2 = -1$ where $II := ee_1 ee_2 ee_3$.
]

A more formal definition follows.

Let $V$ be a finite-dimensional vector space over a field $KK$.

#recall[
	A bilinear form $dot$ is a function $V times V -> KK$ is
	- symmetric, $u dot v = v dot u$
	- linear, $(alpha u + beta v) dot w = alpha u dot w + beta v dot w$
]

#recall[
	The free tensor algebra $V^tensor$ over $V$ has a multiplication $tensor$ which is
	- associative, $(a tensor b) tensor c = a tensor (b tensor c)$
	- scalar compatible, $(lambda a) tensor b = lambda (a tensor b) = a tensor (lambda b)$
	as well as distributive over addition.
]

The tensor algebra $V^tensor = KK plus.circle V plus.circle (V tensor V) plus.circle (V tensor V tensor V) plus.circle dots.c$ splits into graded subspaces; an element $a in underbrace(V tensor dots.c tensor V, k)$ is of _grade $k$_.
Elements can be mixed grade!

#recall[
	A (two-sided) ideal in an algebra is a subspace $I$ for which $z in I$ implies $a z, z a in I$ for any $a$.
]

An ideal behaves like a generalised zero element: anything multiplied by something zero-ish is zero-ish.
Sending everything in an ideal to zero gives another well-defined algebra: this is what _taking the quotient_ by an ideal means.

#define[

	Let $V$ a finite-dimensional vector space with a bilinar form $dot$.
	The associated _Clifford algebra_ is the quotient
	$
		Cl(V, dot) tilde.equiv V^times.circle slash I
	$
	where $I$ is the ideal generated by ${u times.circle u - u dot u | u in V}$.
]

In other words, $Cl(V, dot)$ is what you get if you have a free, associative algebra over $V$ with the rule that $u^2 = u dot u$ for all $u in V$.

#define[
	The _geometric algebra_ $Cl_(p, q)$ is taken to be $Cl(RR^(p + q), g)$ where $g$ is a bilinear form with signature $(p, q)$.
]

= Immediate ramifications

These facts immediately follow from the definition of a geometric algebra.
Let $u, v in V$.

#result[Vectors are invertible: $u^(-1) = u (u dot u)^(-1)$.]

#result[The symmetrised vector product is $u dot v = 1/2 (u v + v u)$.]

#define[Call the antisymmetric part $u wedge v = 1/2 (u v - v u)$.]

#comment[The geometric product $u v = underbrace(u dot v, "scalar") + underbrace(u wedge v, "bivector")$ is of _mixed grade_.]

#result[
	#show sym.arrow.double.long.l.r: pad.with(x: 1em)
	(Anti)commutativity relates to perpendicularity:
	$
		u &parallel v &<==> u v &= v u &<==> u v &= u dot v \
		u &perp v &<==> u v &= -v u &<==> u v &= u wedge v \
	$
]

== Higher-grade elements

#define[
	- A _$k$-blade_ is an element of the form $u_1 u_2 dots.c u_k$ where $u_i perp u_j$ for $i != j$.
	- A sum of $k$-blades is a _$k$-vector_.
	- A sum of arbitrary blades is a _multivector_.
]

#comment[
	Not all $k$-vectors are blades. The simplest counterexample is $ee_1 ee_2 + ee_3 ee_4$.
]

#result[
	If $dim V = n$, then the geometric algebra has dimension $2^n$ and splits into $n$ graded subspaces:
	$
		underbrace(Cl(V, g), 2^n) tilde.equiv
		underbrace(RR, binom(n, 0)) plus.circle
		underbrace(V, binom(n, 1)) plus.circle
		underbrace(V wedge V, binom(n, 2)) plus.circle
		dots.c plus.circle
		underbrace(V^(wedge n), binom(n, n))
	$
]

#define[
	Grade projection $grade(quad, k) : Cl(V, g) -> V^(wedge k)$.
]

#result[
	The geometric product between a $a$-vector $A$ and a $b$-vector $B$ has grades:
	$ A B =
		underbrace(grade(A B, abs(a - b)), A bullet B) +
		grade(A B, abs(a - b) + 2) +
		dots.c +
		grade(A B, a + b - 2) +
		underbrace(grade(A B, a + b), A wedge B)
	$
]

#define[
	All you _need_ is $A B$ and $grade(quad, k)$, but you can define a zoo of products:
	$
		#[(wedge product)]&
			& space quad A wedge B &= grade(A B, a + b) \
		#[(right contraction)]&
			& A rcont B &= grade(A B, a - b) \
		#[(left contraction)]&
			& A lcont B &= grade(A B, b - a) \
		#[(commutator product)]&
			& A times B &= inline(1/2) (A B - B A) \

	$
]
See @ga-product-identities[identities involving these products].
#comment[
	A $k$-blade $A$ defines a $k$-dimensional subspace of $V$:
	$
		[A]:=span{u in V | u wedge A = 0}
	$
]


= The rotation formalism

#recall[
	An orthogonal transformation is a linear map $A : V -> V$ which preserves the bilinear form so that $A(u) dot A(v) = u dot v$ for all $u, v in V$.
]


#result[
	If $u in V$ is nonzero, then $ v |-> u v u^(-1) $ is a reflection which flips every direction orthogonal to $u$.
]

#theorem[
	_(Cartan--Dieudonné.)_
	Any orthogonal transformation on $V$ is a composition of at most $dim V$ reflections.
]

#result[
	Any orthognoal transformation is of the form
	$ u |-> R u R^(-1) $
	where $R = u_1 u_2 dots.c u_k$ for $1$-vectors $u_i$ which we may take to be units $u_i^2 = plus.minus 1$.
]

#example[
	Find a rotation sending $u := 3ee_1 + 2ee_2$ to $v := 2ee_2 + 3ee_3$.

	Let $lambda := norm(u) = norm(v)$. Let $R := (1 + (v u)/lambda^2)$.
	It follows that $R u = v R$ and hence $v = R u R^(-1)$.
	Explicitly, $R = (17 - 6 ee_1 ee_2 - 6 ee_2 ee_3 - 9 ee_1 ee_3) slash 13$.
]

== The magic rotor formula

#define[
	Define the _average conjugate of $A$ with over the subspace $U subset.eq G$_ as
	$
		EE_U {A} = 1/(dim U) sum_(g in cal(U)) g A g^(-1)
	$
	where $cal(U)$ is an orthogonal basis for the subspace $U subset.eq G$.
]

#result[
	 $EE_G {A} = grade(A, 0)$ if $n$ is even else $EE_G {A} = grade(A, 0) + grade(A, n)$.
]

#result[
	If $A = grade(A, q)$ is a $q$-vector, then:
	$
		EE_grade(G, k){A} = [2binom(n, k)^(-1) sum_(m "even") binom(q, m) binom(n - q, k - m) - 1] (-1)^(k q) A
	$
]
#proof[See @multivector-deriv-identities[this note].]

#define[
	If $I = {i_1, ..., i_k}$ then define multi-index notation by $ee_I := ee_i_1 dots.c ee_i_k$ where $i_1 < dots.c < i_k$.
]

#theorem[
	If ${e_1, ..., e_n}$ and ${f_1, ..., f_n}$ are orthogonal bases related by a rotation, then
	$
		S := lambda sum_(I subset.eq {1, ..., n}) f_I e_I^(-1)
	$
	is a rotor satisfying $S e_i rev(S) = f_i$
	where $lambda in RR$ is a normalisation factor ensuring $S rev(S) = 1$,
]
#proof[
	There must be some rotor $R$ such that $f_i = R e_i rev(R)$.
	Then
	$
		sum_I f_I e_I^(-1)
		= sum_I R e_I rev(R) e_I^(-1)
	 	= 2^n R space EE_G {rev(R)}
		= 2^n R grade(R, 0)
	$
	and hence $S = lambda R$ where $lambda 2^n grade(R, 0) in RR$.
]

== Some topological features of rotations

#define[
	The (special) orthongonal groups are
	$
		upright("O")(V, g) &= {A in "GL"(V) | A^* A = A A^* = bb(1)} \
		"SO"(V, g) &= {A in upright("O")(V, g) | det A  = 1} \
	$
	where $A^*$ is the adjoint of $A$ with respect to the bilinear form $g$, satisfying $g(A u, v) = g(u, A^* v)$ for all $u, v in V$.
]

#define[
	The _pin group_ is the subgroup of elements products of unit vectors.
	$ "Pin"(V) = { u_1 u_2 dots.c u_k mid(|) u_i in V, u_i^2 = plus.minus 1 } $
	The _spin group_ $ "Spin"(V, q) = "Pin"(V, q) sect Cl(V, q)^+ $ is the subgroup of even-grade elements in the pin group.
]

#result[
	$"Spin"(V, q)$ is a double cover of $"SO"(V, q)$.
]