#import "@local/notes:0.1.0"
#show: notes.style

#let refl(A, x) = $"refl"_#A (#x)$
#let refl(A, x) = $"refl"(#A, #x)$
#let up(x) = $"up"(#x)$

#let (x, p, E) = ($x$, $p$, $E$).map(math.bold)

#import "@local/common:0.1.0": *

#let ((eo, eoo), (Xeo, Xeoo)) = if false {
	// Leo's old notation
	(($cal(o)$, $oo$), ($X_cal(o)$, $X_oo$))
} else {
	// Joan's preferred notation
	(($n_0$, $n_oo$), ($X_0$, $X_oo$))
}

#show math.frac: it => {
	if it.num == [1] and it.denom == [2] {
		math.inline(it)
	} else {
		it
	}
}

#let trans(p, ..args) = {
	if args.pos().len() == 1 { $trans(#p)[#args.pos().at(0)]$ }
	else { $mono(T)_#p$ }
}

= Reflections generated by blades in @cga[CGA]

The idea is: understand rotors by classifying all reflections.


We have a nice @cga-blade-classification[classification of all blades] given by
$
X = cases(
	#E eoo,
	trans(#p, #E),
	trans(#p, eo wedge #E wedge eoo),
	trans(#p, (eo plus.minus rho^2/2 eoo) wedge #E),
)
$ <cga-blades>
but what about a nice classification of all versors?

Any invertible blade $A$ defines two transformations: a reflection of the vector space #underline[within] $A$ or #underline[across] $A$.
In a homogeneous setting, these are the same, since they differ only by an overall sign.

Not all orthogonal transformations are generated by reflections by blades.
However, blades have geometrical interpretations via @cga-ipns-opns-summary[IPNS/OPNS], so they are a useful class of transformations to study.

== Reflections as operators with nice properties

See to @multivector-proj-rej[the note on projections and reflections].
Let's define the operator
$
refl(A, x) := A^star x A^(-1) = rej(u, A) - proj(u, A)
$
which reflects the multivector $x$ #underline[within] $A$.
I.e., all the dimensions lying in the blade $A$ are negated.

We have a simple composition rule:
$
refl(A, refl(B, x))
= A^star B^star x B^(-1) A^(-1)
= (A B)^star x (A B)^(-1)
= refl(A B, x)
$
In fact, $refl(A, -)$ is an automorphism. In particular, $refl(A, x^(-1)) = refl(A, x)^(-1)$.
If $f$ is some automorphism, then $f(refl(A, B)) = refl(f(A), f(B))$.

== Reflections and the embedding map


We have some nice properties: $"up" compose "refl" = "relf" compose "up"$
$
refl(#E, up(#x))
&= refl(#E, eo) + refl(#E, x) + refl(#E, 1/2 x^2 eoo) \
&= eo+ refl(#E, #x) + 1/2 #x^2 eoo \
&= up(refl(#E, #x))
$

$
refl(eo wedge eoo, up(#x))
&= refl(eo wedge eoo, eo) + #x + 1/2 x^2 refl(eo wedge eoo, eoo) \
&= -eo + #x - 1/2 x^2 eoo \
&= -up(-#x) 
$

== Reflections of blades

Everything in @cga-blades except directions $#E wedge eoo$ and zero-radius rounds $trans(#p, eo wedge #E)$ are invertible so generate reflections.

=== Reflection in a dual flat

$
refl(trans(#p, #E), up(#x))
&= trans(#p, refl(#E, up(#x - #p))) \
&= trans(#p, up(refl(#E, #x - #p))) \
&= up(refl(#E, #x - #p) + #p) \
$

=== Reflection in a flat

$
refl(trans(#p, eo wedge #E wedge eoo), up(#x))
&= trans(#p, refl(eo wedge eoo wedge #E^star, up(#x - #p))) \
&= trans(#p, refl(eo wedge eoo, refl(#E^star, up(#x - #p)))) \
&= trans(#p, refl(eo wedge eoo, up(refl(#E, #x - #p)))) \
&= trans(#p, -up(-refl(#E, #x - #p)))) \
&= -up(#p - refl(#E, #x - #p)))) \
$


=== Reflection in a round

We use the identities
$
refl(eo plus.minus 1/2 rho^2 eoo, eo) &= minus.plus 1/2 rho^2 eoo \
refl(eo plus.minus 1/2 rho^2 eoo, eoo) &= minus.plus 2/rho^2 eo \
$
we find
$
refl(trans(#p, (eo plus.minus 1/2 rho^2 eoo) wedge #E), up(#x))
&= trans(#p, refl(eo plus.minus 1/2 rho^2 eoo, refl(#E, up(#x - #p)))) \
&= trans(#p, refl(eo plus.minus 1/2 rho^2 eoo, up(refl(#E, #x - #p)))) \
&= trans(#p, minus.plus 1/2 rho^2 eoo + refl(#E, #x - #p) minus.plus 1/2 (#x - #p)^2 2/rho^2 eo) \
&= minus.plus ((#x - #p)/rho)^2 trans(#p, eo minus.plus rho^2/refl(#E, #x - #p) + 1/2 (rho^2/(#x - #p))^2 eoo) \
&= minus.plus ((#x - #p)/rho)^2 trans(#p, up(minus.plus rho^2/refl(#E, #x - #p))) \
&= minus.plus ((#x - #p)/rho)^2 up(#p minus.plus rho^2/refl(#E, #x - #p)) \
$

== Fixed points of reflections

Suppose $#x in sans("OPNS")(X)$ so $up(#x) wedge X = 0$.

$
	refl(X, up(#x)) = A^star up(#x) A^(-1) = (A^star rcont up(#x)) A^(-1) = (up(#x) lcont A) A^(-1) = up(#x)
$

So $sans("OPNS")(X)$ are fixed points of $#x |-> refl(X, up(#x))$.

Similarly, suppose $#x in sans("IPNS")(X)$ so $up(#x) lcont X = 0$.
$
	refl(X, up(#x)) = A^star up(#x) A^(-1) = (A^star wedge up(#x)) A^(-1) = (up(#x) wedge A) A^(-1) = up(#x)
$
So $sans("IPNS")(X)$ are fixed points of $#x |-> refl(X, up(#x))$.
