#import "@local/notes:0.1.0"
#show: notes.style

#import "@local/common:0.1.0": *

= The spin groups

#env[Define][
Let $V$ be a vector space with quadratic form $q$.
Let $SS &:= {u in V mid(|) q(u) = plus.minus 1}$ be the generalised unit sphere.
$
  "Pin"(V, q) &:= {u_1 u_2 dots.c u_k mid(|) u_i in SS} \
  "Spin"(V, q) &:= {u_1 u_2 dots.c u_(2 k) mid(|) u_i in SS} \
  	&= "Pin"(V, q) sect Cl(V, q)^+ \
$
]

== Nit-picking definitions

In @lawson1989[definition 2.3], the following subgroups of $Cl(V, q)$ are defined:

- $Cl^times (V, q) = {phi in Cl(V, q) | exists phi^(-1)}$, or just invertible elements
- $upright(P)(V, q)$ is the subgroup of $Cl^times (V, q)$ generated by vectors $v in V$ with $v^2 != 0$
- $"Pin"(V, q)$ is the subgroup of $upright(P)(V, q)$ generated by vectors $v in V$ with $v^2 != plus.minus 1$
- Finally, $"Spin"(V, q)$ is the even subgroup $"Pin"(V, q) sect Cl^0(V, q)$

Later on, @lawson1989[equation 2.24] states the pin group is
$
  "Pin"(V, q) = {u_1 u_2 dots.c u_k in "P"(V, q) mid(|) u_i^2 = plus.minus 1} "."
$

Why bother with defining $"P"(V, q)$, and $Cl^times (V, q)$, for that matter? Is it true that:
$
  "Pin"(V, q) = {u_1 u_2 dots.c u_k mid(|) u_i^2 = plus.minus 1} space "?"
$
That would be cleaner.

I'm going to say "yes".