#import "@local/notes:0.1.0"
#show: notes.style


#let normal = $cal(N)$

= Flow matching

#emph[Following notes from @holderrieth2025.]

Flow matching is a way of modelling a target distribution $p_"data"$ by learning how to transform samples from a simpler distribution $p_"noise"$ into target samples by moving them along a learned _flow_.

Specifically, we learn a time-varying vector field $arrow(u)_t (x)$ for $0 <= t <= 1$ with the property that, given an initial sample $x_0 ~ p_"noise"$, pushing the sample along the flow of $arrow(u)_t$ by solving the differential equation
$
  (dif x_t)/(dif t) = arrow(u)_t (x_t)
$ <ode>
for $t = 0 -> 1$ results in a solution such that $x_1 ~ p_"data"$.
In other words, the flow sends samples distributed as $p_"noise"$ to samples distributed as $p_"data"$.


== Probability paths

To come up with a flow which transforms $p_"noise"$ into $p_"data"$, we need to define the "intermediate" probability distributions, $p_t$.
A *probability path* is a family of probability distributions parametrised by $0 <= t <= 1$.

We will first consider _conditional_ probability paths for a single data point, and later consider the full probability path $p_"noise" |-> p_"data"$.

=== The continuity equation

If we imagine that the probability path $p_t$ is the time-varying density of a fluid with velocity $arrow(u)_t$ then the _continuity equation_
$
  (partial p_t (x))/(partial t) = -nabla dot (p_t (x) arrow(u)_t (x))
$ <continuity-eq>
is satisfied if the amount of fluid (or total probability) is conserved.

This defines the _flow_ $arrow(u)_t$ associated with a probability path.

Note that, if $x_t ~ p_t$ is a particle in the fluid, then $dot(x)_t = arrow(u)_t (x_t)$ by definition.
This relates the "ODE perspective" of @ode to the "physics perspective" in terms of particle flow.


=== Conditional probability paths
Let $z in RR^d$ be a data point.
Consider the path $t |-> p_t (dot | z)$ through the space of distributions on $RR^d$ given by
$
  p_t (dot | z) = normal(alpha_t z, beta_t^2 II)
$ <cond-path>
where $alpha_t$ and $beta_t$ are fixed _noise schedulers_, for example $alpha_t = t$ and $beta_t = 1 - t$.
This is the _Gaussian probability path_.
It starts at the noise distribution $p_0 = normal(0, II)$ and ends at the Dirac delta $p_1 = delta_z$.

What is the flow $arrow(u)_t (x|z)$ associated to $p_t (x|z)$?

Note that if $x_t in p_t (dot|z)$ then we can write
$
  x_t = alpha_t z + beta_t epsilon, quad epsilon ~ normal(0, II)
$
and so $dot(x)_t = dot(alpha)_t z + dot(beta)_t epsilon$.
But note that $epsilon = (x_t - alpha_t z)/beta_t$ so we get
$
  (dif x_t)/(dif t) = dot(alpha)_t z + dot(beta)_t/beta_t (x_t - alpha_t z) = (dot(alpha)_t - dot(beta)_t/beta_t alpha_t) z + dot(beta)_t/beta_t x_t = arrow(u)_t (x_t | z)
$
which gives us the _conditional vector field_ for the Gaussian probability path.

#notes.result-box[
  Since $p_t (x|z)$ and $arrow(u)_t (x|z)$ together solve the continuity equation, then a time-varying random variable
  $
    x_0 ~ p_0 (dot|z) = normal(0, II)
  $
  which satisfies the ODE
  $
    dot(x)_t = arrow(u)_t (x_t|z)
  $
  will be distributed as
  $
    x_t ~ p_t (dot|z)
  $
  for all $0 <= t <= 1$, in particular $x_1 ~ p_1(dot|z) = delta_z$ so $x_1 = z$.
]

=== Marginal probability path


We can construct a _marginal_ probability path
$
  p_t (x) = integral p_t (x|z) p_"data" (z) dif z
$ <marginal>
by integrating over conditional probability paths from @cond-path.

If we have a conditional probability path $p_t (x|z)$ generated by a conditional vector field $arrow(u)_t (x|z)$, then what vector field $arrow(u)_t (x)$ is associated with the marginal probability path?

We know that $p_t (x)$ and $arrow(u)_t$ together must satisfy the continuity equation
$
  dot(p)_t (x) = -nabla dot (p_t arrow(u)_t)  (x)
  .
$
Substituting the definition @marginal,
$
  dot(p)_t (x) &= integral dot(p)_t (x|z) p_"data" (z) dif z \
  &= - integral nabla dot (p_t (x|z) arrow(u)_t (x|z)) p_"data" (z) dif z \
  &= - nabla dot (integral p_t (x|z) arrow(u)_t (x|z) p_"data" (z) dif z) \
$
so we have to vector fields whose divergences are equal everywhere.
If we equate them,
$
  p_t (x) arrow(u)_t (x) = integral p_t (x|z) arrow(u)_t (x|z) p_"data" (z) dif z
  ,
$
then we get the marginal vector field:
$
  arrow(u)_t (x) = integral arrow(u)_t (x|z) [(p_t (x|z) p_"data" (z))/(p_t (x))] dif z
  
$ <utx>

#notes.result-box[
  Since $p_t (x)$ and $arrow(u)_t (x)$ together solve the continuity equation, then a time-varying random variable
  $
    x_0 ~ p_0 = normal(0, II)
  $
  which satisfies the ODE
  $
    dot(x)_t = arrow(u)_t (x_t)
  $
  will be distributed as
  $
    x_t ~ p_t
  $
  for all $0 <= t <= 1$, in particular $x_1 ~ p_1(dot) = p_"data"$.
]

= Learning $arrow(u)_t$

Suppose we wish to approximate the marginal vector field $arrow(u)_t$ with a neural network $arrow(u)^theta_t$ with parameters $theta$.
The _flow matching_ loss function is defined as
$
  cal(L)(theta) = EE_(t,x) [ norm(arrow(u)_t^theta (x) - arrow(u)_t (x))^2]
$ <loss>
where $t ~ "Uniform"(0, 1)$ and $x ~ p_t$.
In other words, we try to match the outputs the model $arrow(u)^theta (x)$ with the true vector field $arrow(u)_t (x)$ at every possible input $(t, x)$.

Evaluating this loss function amounts to drawing $t$ and then $x ~ p_t$, or equivalently drawing $t$ and $z ~ p_"data"$ then $x ~ p_t (dot | z)$.
Assuming a Gaussian probability path where $p_t (dot | z) = normal(alpha_t z | beta_t^2 t)$, this second method amounts to picking a sample $z$ and adding some noise to it, $x = alpha_t z + beta_t epsilon$ for $epsilon in normal(0, II)$.

Note that $arrow(u)_t (x)$ cannot be evaluated directly, since @utx is intractable.
However, if we expand @loss we get a cross term
$
  EE_(t,x) [arrow(u)_t^theta (x) arrow(u)_t (x)]
  = integral_0^1 dif t integral dif x thin p_t (x) arrow(u)_t^theta (x) integral dif z thin arrow(u)_t (x|z) [(p_t (x|z) p_"data" (z))/(p_t (x))] \
  = integral_0^1 dif t integral dif z thin p_"data" (z) integral dif x thin p_t (x|z) arrow(u)_t^theta (x) arrow(u)_t (x|z)  \
  = EE_(t,z,x~p_t (dot|z)) [arrow(u)_t^theta (x) arrow(u)_t (x|z)]
$
which only uses the conditional vector field.

We can put this cross term back into the square to obtain a simpler loss function plus a constant term.
$
  cal(L)(theta) =
  underbrace(EE_(t, z, x)[norm(arrow(u)_t^theta (x) - arrow(u)_t (x|z))^2], cal(L)_C (theta))
  + underbrace(norm(arrow(u)_t (x))^2 - norm(arrow(u)_t (x|z))^2, #[independent of $theta$] )
$
Therefore, by minimising the _conditional flow matching_ loss $cal(L)_C (theta)$, we minimise the flow matching loss $cal(L)(theta)$.

The final loss function is therefore
$
  cal(L)_C (theta)
  &= EE_(t,z,x)[norm(arrow(u)_t^theta (x) - arrow(u)_t (x|z))^2] 
$
where $t~"Uniform"[0,1]$, $z~p_"data"$ and $x~p_t (dot | z)$.
In the Gaussian case with @cond-path this simplifies even further to:

#notes.result-box[
  Gaussian conditional flow matching loss:
  $
    cal(L)_C (theta) &=  EE_(t,z,epsilon)[
    norm( arrow(u)_t^theta (alpha_t z + beta_t epsilon) - (dot(alpha)_t z + dot(beta)_t epsilon) )^2 ]
  $
  where $t~"Uniform"[0,1]$, $z~p_"data"$ and $epsilon ~ normal(0, II)$.
]



= Summary of the Gaussian case

Let $epsilon ~ normal(0, 1)$.

Conditional probability flow:
$
  x ~ p_t (dot | z) = normal(alpha_t z,beta_t^2)
  <==>
  x = alpha_t z + beta_t epsilon
$
Conditional vector field:
$
  arrow(u)_t (x|z) = dot(x)_t = dot(alpha)_t z + dot(beta)_t epsilon = (dot(alpha)_t - dot(beta)_t/beta_t alpha_t) z + dot(beta)_t/beta_t x_t
$
Conditional loss:
$
  cal(L)(theta)
  &= EE_(t~"Unif"[0,1], z~p_"data", x~p_t (dot | z))[norm(arrow(u)_t^theta (x) - arrow(u)_t (x|z))^2] \
  &= EE_(t~"Unif"[0,1], z~p_"data", epsilon~normal(0,1))[
    norm( arrow(u)_t^theta (alpha_t z + beta_t epsilon) - (dot(alpha)_t z + dot(beta)_t epsilon) )^2
  ]
$
So to train $theta$ to minimise $cal(L)$:
#import "@preview/lovelace:0.3.0"
#lovelace.pseudocode-list[
  + *given* $theta$ and (?)
    + $t ~ "Unif"[0, 1]$
    + $z ~ p_"data"$
    + $epsilon ~ normal(0, 1)$
    + $nabla theta <- "gradient"_theta (norm(arrow(u)_t^theta (alpha_t z + beta_t epsilon) - (dot(alpha)_t z + dot(beta)_t epsilon))^2)$
]

= Details I have ignored

You can add a stochastic term to get a diffusion model where we solve an SDE instead of an ODE.

== Score functions

The conditional score function is $nabla ln p_t (x)$ and the marginal score function is
$
  nabla ln p_t (x)
  &= 1/(p_t (x)) integral nabla p_t (x|z) p_"data" (z) dif z \
  &= integral nabla ln p_t (x|z) [(p_t (x|z) p_"data" (z))/(p_t (x))] dif z
$

For a Gaussian conditional probability path, the conditional score function is:
$
  nabla ln p_t (x|z) = (alpha_t z - x)/beta_t^2
$

